services:
  mongo:
    image: 'mongo:latest'
    container_name: 'edukate-mongo'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_DATABASE=edukate'
    ports:
      - '27017:27017'
    volumes:
      - './mongo-data:/data/db'

  minio:
    image: 'minio/minio:latest'
    container_name: 'edukate-minio'
    environment:
      - 'MINIO_ROOT_USER=minio-admin'
      - 'MINIO_ROOT_PASSWORD=minio-secret'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio-data:/data'
    command: server /data --console-address ":9001"
