namespace: default
imageRegistry: registry.digitalocean.com/edukate-container-registry
dockerTag: latest
replicaCount: 1

autoscaling:
  enabled: false

env: staging
initCerts:
  enabled: false
profile: dev
pullPolicy: IfNotPresent

backend:
  name: backend
  imageName: edukate-backend
  profile: prod,secure,notifier
  pullPolicy: Always
  containerPort: 5800
  managementPort: 5801
  clusterIP: null
  applicationProperties:

frontend:
  name: frontend
  imageName: edukate-frontend
  pullPolicy: Always
  containerPort: 80

gateway:
  name: gateway
  imageName: edukate-gateway
  pullPolicy: Always
  containerPort: 5810
  managementPort: 5811
  applicationProperties:

notifier:
  name: notifier
  imageName: edukate-notifier
  pullPolicy: Always
  containerPort: 5820
  managementPort: 5821
  clusterIP: null
  applicationProperties:

ingress:
  tls:
    profile: "staging"
    enabled: false

s3:
  enabled: true
  secretName: s3-secrets

mongodb:
  enabled: true
  secretName: mongodb-secrets
  secretKey:
    backend: connectionString
    notifier: notifierConnectionString

jwt:
  secretName: jwt
  secretKey: key
