namespace: default
imageRegistry: registry.digitalocean.com/edukate-container-registry
dockerTag: latest
replicaCount: 1

autoscaling:
  enabled: false

env: staging
initCerts:
  enabled: false
profile: dev
pullPolicy: IfNotPresent

backend:
  name: backend
  imageName: edukate-backend
  pullPolicy: Always
  containerPort: 5800
  managementPort: 5801
  clusterIP: null
  applicationProperties:

frontend:
  name: frontend
  imageName: edukate-frontend
  pullPolicy: Always
  containerPort: 80

gateway:
  name: gateway
  imageName: edukate-gateway
  pullPolicy: Always
  containerPort: 5810
  managementPort: 5811
  applicationProperties:


ingress:
  tls:
    enabled: false

s3:
  enabled: true
  secretName: s3-secrets

mongodb:
  enabled: true
  secretName: mongodb-secrets
  secretKey: connectionString

jwt:
  secretName: jwt
  secretKey: key
