namespace: default
imageRegistry: registry.digitalocean.com/edukate-container-registry
replicaCount: 1

autoscaling:
  enabled: false

env: staging
initCerts:
  enabled: false
profile: dev
pullPolicy: IfNotPresent

backend:
  name: backend
  pullPolicy: Always
  imageName: edukate-backend
  containerPort: 5800
  managementPort: 5801
  clusterIP: null
  applicationProperties:

frontend:
  name: frontend
  pullPolicy: Always
  imageName: edukate-frontend
  containerPort: 80

gateway:
  name: gateway
  imageName: edukate-gateway
  containerPort: 5810
  managementPort: 5811
  applicationProperties:
  svc:
    annotations: {}
    spec: {}

ingress:
  tls:
    enabled: false

s3:
  enabled: true
  secretName: s3-secrets

mongodb:
  enabled: true
  secretName: mongodb-secrets
  secretKey: connectionString
