namespace: default
imageRegistry: registry.digitalocean.com/edukate-container-registry
replicaCount: 1

profile: prod,secure

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env: staging
pullPolicy: IfNotPresent

ingress:
  tls:
    enabled: true
  host: "edukate.mooo.com"

s3:
  enabled: true
  secretName: s3-secrets

mongodb:
  enabled: true
  secretName: mongodb-secrets
  secretKey:
    backend: connectionString
    notifier: notifierConnectionString
