spring.application.name=edukate-notifier
spring.docker.compose.enabled=false
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
server.port=5820

management.server.port=5821
management.endpoints.web.exposure.include=health,info,loggers,prometheus
management.endpoint.prometheus.access=read_only
management.metrics.tags.application=${spring.application.name}
logging.group.edukate=io.github.sanyavertolet

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/swagger/notifier/api-docs
springdoc.swagger-ui.enabled=false

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES}

gateway.url=https://edukatemeplease.online

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

edukate.email.from=${EMAIL_FROM}
