apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edukate-letsencrypt-issuer-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lxnfrolov@gmail.com
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key-staging-cert
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edukate-letsencrypt-issuer-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lxnfrolov@gmail.com
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key-prod-cert
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx