apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edukate-letsencrypt-issuer-{{ .Values.ingress.tls.profile }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-{{ eq .Values.ingress.tls.profile "staging" | ternary "staging-" "" }}v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.tls.email }}
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key-cert-{{ .Values.ingress.tls.profile }}
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token