apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.gateway) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pod.common.labels" (merge (dict "service" .Values.gateway ) .) | nindent 8 }}
      annotations:
        {{- include "pod.common.annotations" (dict "service" .Values.gateway ) | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: gateway
          {{- include "spring-boot.common" (merge (dict "service" .Values.gateway) .) | nindent 10 }}
          env:
            {{- include "spring-boot.common.env" (merge (dict "service" .Values.gateway) .) | nindent 12 }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: {{ .Values.jwt.secretKey }}
            - name: HOST_NAME
              value: {{ .Values.ingress.host }}
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
          {{- include "spring-boot.management" .Values.gateway | nindent 10 }}
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.gateway) | indent 10 | trim }}
        - name: migrations-data
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gateway.name }}-config
  namespace: {{ .Values.namespace }}
data:
  application.properties: |
    {{ if .Values.gateway.applicationProperties }}
    {{- .Values.gateway.applicationProperties | nindent 4 }}
    {{ end }}


---

apiVersion: v1
kind: Service
metadata:
{{- include "service.common.metadata" (dict "service" .Values.gateway) | nindent 2 }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    {{- include "service.common.ports" (dict "service" .Values.gateway) | nindent 4 }}
  selector:
    {{- include "service.common.selectors" (dict "service" .Values.gateway) | nindent 4 }}
