apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edukate-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: edukate-letsencrypt-issuer-{{ .Values.ingress.tls.profile }}
  labels:
    app: edukate-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: 80
          - path: "/swagger-ui"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: 80
      {{ if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{ end }}

  {{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: letsencrypt-nginx-private-key-cert-{{ .Values.ingress.tls.profile }}
  {{ end }}
