apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "common.labels" (merge (dict "service" .Values.notifier) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: notifier
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ include "pod.common.labels" (merge (dict "service" .Values.notifier ) .) | nindent 8 }}
      annotations:
        {{ include "pod.common.annotations" (dict "service" .Values.notifier ) | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: notifier
          {{ include "spring-boot.common" (merge (dict "service" .Values.notifier) .) | nindent 10 }}
          env:
            {{ include "spring-boot.common.env" (merge (dict "service" .Values.notifier) .) | nindent 12 }}
            {{ if .Values.mongodb.enabled }}
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: {{ .Values.mongodb.secretKey.notifier }}
            {{ end }}
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
          {{ include "spring-boot.management" .Values.notifier | nindent 10 }}
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.notifier) | indent 10 | trim }}
        - name: migrations-data
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.notifier.name }}-config
  namespace: {{ .Values.namespace }}
data:
  application.properties: |
    {{ if .Values.notifier.applicationProperties }}
    {{ .Values.notifier.applicationProperties | nindent 4 }}
    {{ end }}


---

apiVersion: v1
kind: Service
metadata:
{{ include "service.common.metadata" (dict "service" .Values.notifier) | nindent 2 }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    {{ include "service.common.ports" (dict "service" .Values.notifier) | nindent 4 }}
  selector:
    {{ include "service.common.selectors" (dict "service" .Values.notifier) | nindent 4 }}
