{{ if and .Values.postgresql.enabled (contains .Values.profile "dev") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: postgresql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: postgresql
    spec:
      restartPolicy: Always
      containers:
        - name: postgresql
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: edukate
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secretName }}
                  key: "username"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secretName }}
                  key: "password"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: postgresql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/k8s/postgres

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      io.kompose.service: postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    io.kompose.service: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

{{ end }}
