gateway:
  backend:
    url: http://backend
  notifier:
    url: http://notifier

auth:
  jwt:
    expirationSeconds: 3600
    secret: ${JWT_SECRET}
  hostname: ${HOST_NAME}

springdoc:
  api-docs:
    enabled: true
    path: /swagger/gateway/api-docs
  swagger-ui:
    enabled: true
    urls:
      - name: edukate-gateway
        url: /swagger/gateway/api-docs
      - name: edukate-backend
        url: /swagger/backend/api-docs
      - name: edukate-notifier
        url: /swagger/notifier/api-docs
    config-url: /swagger/gateway/api-docs/swagger-config
    path: /swagger
    disable-swagger-default-url: true
    urls-primary-name: edukate-gateway
    operations-sorter: alpha

spring:
  application:
    name: gateway
  liquibase:
    enabled: false
  profiles:
    default: prod,secure
  cloud:
    gateway:
      routes:
        - id: gateway_route
          uri: no://op
          predicates:
            - Path=/api/*/auth/*,/swagger/gateway/api-docs/**
        - id: notifier_route
          uri: ${gateway.notifier.url}
          predicates:
            - Path=/api/*/notifications/**,/swagger/notifier/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: api_route
          uri: ${gateway.backend.url}
          predicates:
            - Path=/api/**,/swagger/backend/api-docs/**
          filters:
            - RemoveRequestHeader=Cookie

---
server:
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    path: /error
  port: 5810
management:
  server:
    port: 5811
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true

---
logging:
  level:
    org:
      springframework: DEBUG
    io:
      github:
        sanyavertolet: DEBUG

---
spring:
  config:
    activate:
      on-profile: kubernetes

---
spring:
  config:
    activate:
      on-profile: prod
